name = "Architects Land - Terre des Civilisations (Server)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03a13d73c32884c37c1d4b357a244694ac416ee08b8f5073a0232ab705d447b4"

[versions]
minecraft = "1.21"
quilt = "0.26.0"
