name = "Architects Land - Terre des Civilisations (Server)"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06f153c90c452bdbaa0e595b8ad93a6a0c175c419de5d7f6f4c1c3b046e2b3fd"

[versions]
minecraft = "1.21"
quilt = "0.26.0"
